### ISSUE TITLE
Config orientdb service as LoadBalancer

### ISSUE THREAD

**Issue by qualitesys** [orientechnologies/orientdb-helm#5]
I wished to configure the orientdb service as a LoadBalancer with session affinity.

I made a change in the statefulset.yaml (adding type: LoadBalancer) but it makes an error (orientdb service exists already).

In fact the yaml files of the chart must not be changed.

After the helm install instruction, I have added :

```
kubectl delete service orientdb
kubectl apply -f orientdb-helm-values-patch.yaml 
```

The file orientdb-helm-values-patch.yaml  is :

```
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: orientdb
  labels:
    app: orientdb
spec:
  ports:
  - port: 2424
    name: binary
  - port: 2480
    name: http
  - port: 2434
    name: hazelcast
  type: LoadBalancer  
  sessionAffinity: ClientIP
  selector:
    app: orientdb
```
PS : this issue because it costed me several days to find the issue and fix it !
